import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';

import Header from '../components/Header/Header';

import '../styles/globals.scss';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'BookStorage App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Header />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
